apiVersion: apps/v1
kind: Deployment
metadata:
  name: spectra-celgene
  labels:
    app: spectra-celgene
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spectra-celgene
  template:
    metadata:
      labels:
        app: spectra-celgene
    spec:
      containers:
      - name: spectra-celgene
        image: relevancelabbigdata/spectra-celgene
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: spectra-celgene
  labels:
    app: spectra-celgene
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    nodePort: 30082
    name: http
  selector:
    app: spectra-celgene